services:
  api:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    ports:
      - "8002:8002"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - api_data:/app/data
    networks:
      - payzee_network
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - payzee_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: redis-server --save 60 1 --loglevel warning

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    restart: unless-stopped
    volumes:
      - redisinsight_data:/db
    networks:
      - payzee_network
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./monitoring/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./monitoring/alerts.yml
        target: /etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - payzee_network
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3002"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_LOG_LEVEL=warn
    networks:
      - payzee_network
    depends_on:
      - prometheus

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - uptime_kuma_data:/app/data
    networks:
      - payzee_network

volumes:
  api_data:
  redis_data:
  redisinsight_data:
  prometheus_data:
  grafana_data:
  uptime_kuma_data:

networks:
  payzee_network:
    driver: bridge
