apiVersion: v1
kind: Service
metadata:
  name: {{ include "payzee.fullname" . }}-redis
  labels:
    {{- include "payzee.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "payzee.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
