apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "payzee.fullname" . }}-redis
  labels:
    {{- include "payzee.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "payzee.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "payzee.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "payzee.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - redis-server
            - --save
            - "60"
            - "1"
          ports:
            - containerPort: {{ .Values.redis.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      {{- if not .Values.redis.persistence.enabled }}
      volumes:
        - name: redis-data
          emptyDir: {}
      {{- end }}
{{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
{{- end }}
